### ISSUE TITLE
Error generating nested options when using the TerraformGenerator class

### ISSUE THREAD

**Issue by ChukwunonsoFrank** [ahzhezhe/terraform-generator#33] opened 2023-07-06 14:34 UTC
**Describe the bug**
When initializing the Terraform generator with `const tfg = new TerraformGenerator({ }}`, I tried to pass in a `required_providers` option for AWS which looks something like this:

```js
const tfg = new TerraformGenerator({
 required_version: '>= 1.2.0',
 required_providers: {
  aws: {
   source: 'hashicorp/aws',
   version: "~> 4.16"
  }
 }
})
```

The `aws` option did not render well in the resulting `terraform.tf` file. This is what I got:

```tf
terraform {
  required_version = ">= 1.2.0"
  required_providers {
    aws {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }
}
```

**To reproduce**
1. Scaffold a mordern Sails.js application with `npx create-sails <project-name>` and complete the prompts to choose which frontend to build your app with(Vue in my case).
2. `cd` into the new directory and run `npm i`.
3. Run `npm i terraform-generator` to install the package.
4. Run the helper generator with `sails generate helper <helper-name>` to generate a test helper to run the Terraform generator.
5. Replace the contents of the file with the following code snippet.

```js
const { TerraformGenerator } = require('terraform-generator')
const path = require('path')

module.exports = {


  friendlyName: 'Generate terraform config',


  description: 'Generate vendor-specific terraform configurations',


  inputs: {

  },


  exits: {

    success: {
      description: 'All done.',
    },

  },


  fn: async function (inputs, exits) {
    try {
      const tfg = new TerraformGenerator({
        required_version: '>= 1.2.0',
        required_providers: {
          aws: {
            source: 'hashicorp/aws',
            version: "~> 4.16"
          }
        }
      })
  
      tfg.provider('aws', {
        region: 'us-west-2'
      })
  
      tfg.resource('aws_instance', 'app_server', {
        ami: 'ami-08d70e59c07c61a3a',
        instance_type: 't2.micro'
      })
  
      // Write the configuration into a terraform.tf file
      const outputDir = path.join('terraform', 'configs');
      tfg.write({ dir: outputDir, format: true });
      return exits.success('Configuration generated successfully...')

    } catch (error) {
      console.log(error)
    }
  }

};
```

6. Open the directory from the terminal and enter into console mode with the `sails console` command.
7. Run the `await sails.helpers.<name-of-helper-in-camelcase>`. So if the helper filename is generate-terraform-config.js, you'd have your command as `await sails.helpers.generateTerraformConfig()`.
8. The generated file should contain the supposed bug.

This issue may not be platform specific but the summary of the complaint is that nested options in the `TerraformGenerator` class do not render properly.

**Expected behavior**
According to the Terraform docs, the `aws` option is supposed to render with a `=` as such:
```tf
terraform {
  required_version = ">= 1.2.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }
}
```

**Additional context**

**Comment by ahzhezhe** [comment] 2023-07-07 02:45
Duplicate of https://github.com/ahzhezhe/terraform-generator/issues/21

Please use map function or Map class

**Closed** 2023-07-07 02:45 UTC

**Comment by ChukwunonsoFrank** [comment] 2023-07-07 11:31
Thanks for the heads up. 👍
