### ISSUE TITLE
Using tags inside resources not output correctly, missing "=" operator

### ISSUE THREAD

**Issue by qeba** [ahzhezhe/terraform-generator#31] opened 2023-02-20 08:49 UTC
**Describe the bug**
I notice when I use tags inside the resources and then generate the Terraform template using the `.write` , the tags will become `tags {}` and I believe it should be  `tags = {}`

Here the full example:
```
import { TerraformGenerator} from 'terraform-generator';
const generator = new TerraformGenerator();

generator.resource('aws_instance', 'example_instance', {
    ami: 'ami-example', 
    instance_type: 't2.micro',
    key_name: 'example_key', 
    tags: {
        Environment: 'Production',
        Application: 'TestingApps',
    },
    iam_instance_profile: 'example_instance_profile', // replace with the name of your IAM instance profile
});

generator.write({
    dir: '.',
    format: true
})
```

And here is the output:
```
resource "aws_instance" "example_instance" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t2.micro"
  key_name      = "example_key"
  tags {
    Environment = "Production"
    Application = "TestingApps"
  }
  iam_instance_profile = "example_instance_profile"
}
```

**Expected behavior**
And I believe the output should be something like:
```
resource "aws_instance" "example_instance" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t2.micro"
  key_name      = "example_key"
  tags          = {
    Environment = "Production"
    Application = "TestingApps"
  }
  iam_instance_profile = "example_instance_profile"
}


```

**Additional context**
Then I also try to output it and print on my terminal using `console.log` i notice that the `=` is also misising. Here example of code i used;
```
//assume continue the above code. 
let result = generator.generate()
console.log(result.tf);
```
and here the output:
```
resource "aws_instance" "example_instance"{
ami = "ami-0c55b159cbfafe1f0"
instance_type = "t2.micro"
key_name = "example_key"
tags {
Environment = "Production"
Application = "TestingApps"
}
iam_instance_profile = "example_instance_profile"
}
```

**Comment by ahzhezhe** [comment] 2023-02-20 12:11
Duplicate of #21 

Please use map function or Map class

**Closed** 2023-02-20 12:11 UTC
